1731145989.9954913 [INFO] [launch]: All log files can be found below /home/tomccd/.ros/log/2024-11-09-16-53-09-991695-tomccd-raspberry4b-25736
1731145989.9960661 [INFO] [launch]: Default logging verbosity is set to INFO
1731145990.6660864 [INFO] [module_supervisor-1]: process started with pid [25739]
1731145990.6687531 [INFO] [module_scanning_interface-2]: process started with pid [25740]
1731145990.6695027 [INFO] [node_io_weigh-3]: process started with pid [25741]
1731145990.6701386 [INFO] [module_weigh-4]: process started with pid [25742]
1731145990.6759844 [INFO] [node_dc_motor-5]: process started with pid [25743]
1731145990.6766887 [INFO] [module_log_file-6]: process started with pid [25744]
1731145993.8263130 [node_io_weigh-3] [ERROR] [1731145993.825457901] [node_io_weigh]: ---- Server Server Module_Input.node_io_weigh: Can't Initalize pigpio ----
1731145993.8501318 [node_io_weigh-3] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1731145993.8505223 [node_io_weigh-3] Can't connect to pigpio at localhost(8888)
1731145993.8509731 [node_io_weigh-3] 
1731145993.8513784 [node_io_weigh-3] Did you start the pigpio daemon? E.g. sudo pigpiod
1731145993.8519163 [node_io_weigh-3] 
1731145993.8556142 [node_io_weigh-3] Did you specify the correct Pi host/port in the environment
1731145993.8562012 [node_io_weigh-3] variables PIGPIO_ADDR/PIGPIO_PORT?
1731145993.8567381 [node_io_weigh-3] E.g. export PIGPIO_ADDR=soft, export PIGPIO_PORT=8888
1731145993.8571820 [node_io_weigh-3] 
1731145993.8576419 [node_io_weigh-3] Did you specify the correct Pi host/port in the
1731145993.8579183 [node_io_weigh-3] pigpio.pi() function? E.g. pigpio.pi('soft', 8888)
1731145993.8583117 [node_io_weigh-3] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1731145993.8640597 [node_dc_motor-5] [ERROR] [1731145993.853507336] [node_dc_motor]: ---- Server Server Module_Motor.node_dc_motor: Can't Initalize pigpio ----
1731145993.8727126 [node_dc_motor-5] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1731145993.8794432 [node_dc_motor-5] Can't connect to pigpio at localhost(8888)
1731145993.8799052 [node_dc_motor-5] 
1731145993.8801963 [node_dc_motor-5] Did you start the pigpio daemon? E.g. sudo pigpiod
1731145993.8804712 [node_dc_motor-5] 
1731145993.8807375 [node_dc_motor-5] Did you specify the correct Pi host/port in the environment
1731145993.8809679 [node_dc_motor-5] variables PIGPIO_ADDR/PIGPIO_PORT?
1731145993.8812361 [node_dc_motor-5] E.g. export PIGPIO_ADDR=soft, export PIGPIO_PORT=8888
1731145993.8816183 [node_dc_motor-5] 
1731145993.8820717 [node_dc_motor-5] Did you specify the correct Pi host/port in the
1731145993.8890853 [node_dc_motor-5] pigpio.pi() function? E.g. pigpio.pi('soft', 8888)
1731145993.8896673 [node_dc_motor-5] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1731145993.9482009 [module_supervisor-1] [INFO] [1731145993.946329568] [Module_Supervisor]: ---- Supervisor: Connect to Server Module_Log_File Successfully ----
1731145994.3084655 [ERROR] [node_io_weigh-3]: process has died [pid 25741, exit code 255, cmd '/home/tomccd/Documents/Code/Python/DATN/install/module_input/lib/module_input/node_io_weigh --ros-args'].
1731145994.3366394 [ERROR] [node_dc_motor-5]: process has died [pid 25743, exit code 255, cmd '/home/tomccd/Documents/Code/Python/DATN/install/module_motor/lib/module_motor/node_dc_motor --ros-args'].
1731145994.9513359 [module_supervisor-1] [WARN] [1731145994.950665596] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Scanning&Interface ----
1731145995.9558578 [module_supervisor-1] [WARN] [1731145995.954926054] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Scanning&Interface ----
1731145996.2088087 [module_supervisor-1] [INFO] [1731145996.208059827] [Module_Supervisor]: ---- Supervisor: Connect to Server Module_Scanning&Interface Successfully ----
1731145996.6683555 [module_scanning_interface-2] [INFO] [1731145996.667707016] [module_scanning_interface]: ----  Server Module_Scanning&Interface: Connect to DB Successfully ----
1731145996.6715920 [module_scanning_interface-2] [ WARN:0@3.371] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
1731145996.6807842 [module_scanning_interface-2] [ERROR:0@3.380] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
1731145997.2146473 [module_supervisor-1] [WARN] [1731145997.213485095] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Input.node_io_weigh ----
1731145998.2230003 [module_supervisor-1] [WARN] [1731145998.221783701] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Input.node_io_weigh ----
1731145999.2310009 [module_supervisor-1] [WARN] [1731145999.230124073] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Input.node_io_weigh ----
1731146000.2356505 [module_supervisor-1] [WARN] [1731146000.234922220] [Module_Supervisor]: ---- Supervisor: Waiting to connect to server Module_Input.node_io_weigh ----
1731146000.2388654 [module_supervisor-1] [ERROR] [1731146000.238090649] [Module_Supervisor]: ---- Supervisor: Can't connect to server Module_Input.node_io_weigh ----
1731146000.2419722 [module_supervisor-1] [ERROR] [1731146000.241222578] [Module_Supervisor]: ---- Supervisor: Initilize System Error ----
1731146000.2533717 [module_log_file-6] [INFO] [1731146000.244157022] [module_log_file]: ---- Server Module_Log_File: Creating Log File... ----
